// GENERATED BY go-gen-graphql-schema
package gqlgen

// THIS CODE IS A STARTING POINT ONLY. IT WILL NOT BE UPDATED WITH SCHEMA CHANGES.

import "github.com/yssk22/go-generators/testdata/e2e/models"

type Resolver struct{}

var query = &models.Query{}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return query }


var mutation = &models.Mutation{}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return mutation }

