name: CI
on: [push, pull_request]
jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.10"
      - uses: actions/cache@v1
        with:
          path: /go/pkg/mod
          key: go-${{ hashFiles('go/**/go.sum') }}
          restore-keys: |
            go-
      - run: go test ./...
